name: Continuous Integration

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Packages
        run: npm install
    outputs:
      timestamp: ${{ steps.current_time.outputs.timestamp }}

  checks:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['Typecheck', 'Eslint', 'Build']
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Run check
        run: |
          case "${{ matrix.check }}" in
            'Typecheck')
              npm run typecheck
              ;;
            'Eslint')
              npm run lint
              ;;
            'Build')
              npm run typecheck && npm run build
              ;;
          esac
