name: Continuous Integration

on:
  push:

jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install Packages
        run: bun install
      - name: Typecheck
        run: bun typecheck
      - name: Eslint
        run: bun lint:repo
      - name: Vitest
        run: bun run test -- --coverage --run
      - name: Build
        run: bun run build
