name: Playwright Tests

on:
  deployment_status:

jobs:
  run_e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Get Email Credentials
        env:
          TEST_EMAIL_CREDENTIALS: ${{ secrets.TEST_EMAIL_CREDENTIALS }}
          TEST_EMAIL_TOKEN: ${{ secrets.TEST_EMAIL_TOKEN }}
        run: |
          touch credentials.json
          echo $TEST_EMAIL_CREDENTIALS >> credentials.json
          touch token.json
          echo $TEST_EMAIL_TOKEN >> token.json
      - name: Install Packages
        run: bun install
      - name: Install Playwright Browsers
        run: bun playwright install --with-deps
      - name: Run Playwright tests
        run: bun run pw:run
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
