name: Playwright Tests

on:
  deployment_status:
jobs:
  run_e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Packages
        run: bun install
      - name: Run Cypress
        run: bun cy:run -- --config baseUrl=$BASE_URL
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
