name: Cypress Tests

on:
  deployment_status:
jobs:
  run_e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM Install
        run: npm ci
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ github.event.deployment_status.environment_url }}
