name: Cypress Tests

on:
  deployment_status:
jobs:
  run_e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/bun.lockb') }}
      - name: Install dependencies and verify Cypress
        run: |
          bun install
          bun cypress install
          bun cypress verify
      - name: Cypress tests
        run: bun cy:run -- --config baseUrl=${{ github.event.deployment_status.environment_url }}
